### PR TITLE
:bug: fix documentation

### PR DESCRIPTION
**Pull request by davidhopkinson26**
Noticed that documentation is not updating on readthedocs.

Addedd in make.bat copied from model_interpreter.  Also updated conf.py with different logic for accessing version.

### CODE REVIEW

**Comment by Decima2014** [comment]
I think readthedocs would use this requirements file here to work which does have that sphinx_rtd_theme installed - https://github.com/lvgig/tubular/blob/main/docs/requirements.txt

**Comment by davidhopkinson26** [comment]
> I think readthedocs would use this requirements file here to work which does have that sphinx_rtd_theme installed - https://github.com/lvgig/tubular/blob/main/docs/requirements.txt

Yes had just realised this and edited the description to remove confusion.  Thanks!

**Comment by davidhopkinson26** [comment]
The docs still aren't building and have numerous errors so there is clearly more work to do here.

**Review by Decima2014 — CHANGES_REQUESTED** [review]
I tried running it locally and got a similar error as to when building the docs for the model_interpreterpackage. The sphinx version is too old:

> Running Sphinx v4.0.2

Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.

I would leave it as unpinned in requirements.txt file

**Comment by davidhopkinson26** [comment]
Closing for now and deleting broken docs files in #348 with a view to fixing and reintroducing later #347

**Pull request closed without merging**
